//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GlyphScript.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace GlyphScriptCompiler.Antlr {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IGlyphScriptListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class GlyphScriptBaseListener : IGlyphScriptListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GlyphScriptParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] GlyphScriptParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GlyphScriptParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] GlyphScriptParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GlyphScriptParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] GlyphScriptParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GlyphScriptParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] GlyphScriptParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>functionCallExp</c>
	/// labeled alternative in <see cref="GlyphScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCallExp([NotNull] GlyphScriptParser.FunctionCallExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>functionCallExp</c>
	/// labeled alternative in <see cref="GlyphScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCallExp([NotNull] GlyphScriptParser.FunctionCallExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>mulDivExp</c>
	/// labeled alternative in <see cref="GlyphScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMulDivExp([NotNull] GlyphScriptParser.MulDivExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>mulDivExp</c>
	/// labeled alternative in <see cref="GlyphScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMulDivExp([NotNull] GlyphScriptParser.MulDivExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>lessThanExpr</c>
	/// labeled alternative in <see cref="GlyphScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLessThanExpr([NotNull] GlyphScriptParser.LessThanExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>lessThanExpr</c>
	/// labeled alternative in <see cref="GlyphScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLessThanExpr([NotNull] GlyphScriptParser.LessThanExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>comparisonExpr</c>
	/// labeled alternative in <see cref="GlyphScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparisonExpr([NotNull] GlyphScriptParser.ComparisonExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>comparisonExpr</c>
	/// labeled alternative in <see cref="GlyphScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparisonExpr([NotNull] GlyphScriptParser.ComparisonExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>idAtomExp</c>
	/// labeled alternative in <see cref="GlyphScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdAtomExp([NotNull] GlyphScriptParser.IdAtomExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>idAtomExp</c>
	/// labeled alternative in <see cref="GlyphScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdAtomExp([NotNull] GlyphScriptParser.IdAtomExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>addSubExp</c>
	/// labeled alternative in <see cref="GlyphScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddSubExp([NotNull] GlyphScriptParser.AddSubExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>addSubExp</c>
	/// labeled alternative in <see cref="GlyphScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddSubExp([NotNull] GlyphScriptParser.AddSubExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>greaterThanExpr</c>
	/// labeled alternative in <see cref="GlyphScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGreaterThanExpr([NotNull] GlyphScriptParser.GreaterThanExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>greaterThanExpr</c>
	/// labeled alternative in <see cref="GlyphScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGreaterThanExpr([NotNull] GlyphScriptParser.GreaterThanExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>notExpr</c>
	/// labeled alternative in <see cref="GlyphScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNotExpr([NotNull] GlyphScriptParser.NotExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>notExpr</c>
	/// labeled alternative in <see cref="GlyphScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNotExpr([NotNull] GlyphScriptParser.NotExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>powerExp</c>
	/// labeled alternative in <see cref="GlyphScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPowerExp([NotNull] GlyphScriptParser.PowerExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>powerExp</c>
	/// labeled alternative in <see cref="GlyphScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPowerExp([NotNull] GlyphScriptParser.PowerExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>xorExp</c>
	/// labeled alternative in <see cref="GlyphScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterXorExp([NotNull] GlyphScriptParser.XorExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>xorExp</c>
	/// labeled alternative in <see cref="GlyphScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitXorExp([NotNull] GlyphScriptParser.XorExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>parenthesisExp</c>
	/// labeled alternative in <see cref="GlyphScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenthesisExp([NotNull] GlyphScriptParser.ParenthesisExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>parenthesisExp</c>
	/// labeled alternative in <see cref="GlyphScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenthesisExp([NotNull] GlyphScriptParser.ParenthesisExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>arrayAccessExp</c>
	/// labeled alternative in <see cref="GlyphScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayAccessExp([NotNull] GlyphScriptParser.ArrayAccessExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>arrayAccessExp</c>
	/// labeled alternative in <see cref="GlyphScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayAccessExp([NotNull] GlyphScriptParser.ArrayAccessExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>valueExp</c>
	/// labeled alternative in <see cref="GlyphScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueExp([NotNull] GlyphScriptParser.ValueExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>valueExp</c>
	/// labeled alternative in <see cref="GlyphScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueExp([NotNull] GlyphScriptParser.ValueExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GlyphScriptParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] GlyphScriptParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GlyphScriptParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] GlyphScriptParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GlyphScriptParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStatement([NotNull] GlyphScriptParser.WhileStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GlyphScriptParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStatement([NotNull] GlyphScriptParser.WhileStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GlyphScriptParser.functionDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDeclaration([NotNull] GlyphScriptParser.FunctionDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GlyphScriptParser.functionDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDeclaration([NotNull] GlyphScriptParser.FunctionDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GlyphScriptParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCall([NotNull] GlyphScriptParser.FunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GlyphScriptParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCall([NotNull] GlyphScriptParser.FunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GlyphScriptParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStatement([NotNull] GlyphScriptParser.ReturnStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GlyphScriptParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStatement([NotNull] GlyphScriptParser.ReturnStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GlyphScriptParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterList([NotNull] GlyphScriptParser.ParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GlyphScriptParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterList([NotNull] GlyphScriptParser.ParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GlyphScriptParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] GlyphScriptParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GlyphScriptParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] GlyphScriptParser.ParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GlyphScriptParser.argumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentList([NotNull] GlyphScriptParser.ArgumentListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GlyphScriptParser.argumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentList([NotNull] GlyphScriptParser.ArgumentListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GlyphScriptParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] GlyphScriptParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GlyphScriptParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] GlyphScriptParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GlyphScriptParser.print"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrint([NotNull] GlyphScriptParser.PrintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GlyphScriptParser.print"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrint([NotNull] GlyphScriptParser.PrintContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GlyphScriptParser.read"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRead([NotNull] GlyphScriptParser.ReadContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GlyphScriptParser.read"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRead([NotNull] GlyphScriptParser.ReadContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GlyphScriptParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] GlyphScriptParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GlyphScriptParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] GlyphScriptParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GlyphScriptParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] GlyphScriptParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GlyphScriptParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] GlyphScriptParser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GlyphScriptParser.defaultDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefaultDeclaration([NotNull] GlyphScriptParser.DefaultDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GlyphScriptParser.defaultDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefaultDeclaration([NotNull] GlyphScriptParser.DefaultDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GlyphScriptParser.initializingDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitializingDeclaration([NotNull] GlyphScriptParser.InitializingDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GlyphScriptParser.initializingDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitializingDeclaration([NotNull] GlyphScriptParser.InitializingDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GlyphScriptParser.immediateValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImmediateValue([NotNull] GlyphScriptParser.ImmediateValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GlyphScriptParser.immediateValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImmediateValue([NotNull] GlyphScriptParser.ImmediateValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GlyphScriptParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] GlyphScriptParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GlyphScriptParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] GlyphScriptParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GlyphScriptParser.arrayOfType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayOfType([NotNull] GlyphScriptParser.ArrayOfTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GlyphScriptParser.arrayOfType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayOfType([NotNull] GlyphScriptParser.ArrayOfTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GlyphScriptParser.arrayLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayLiteral([NotNull] GlyphScriptParser.ArrayLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GlyphScriptParser.arrayLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayLiteral([NotNull] GlyphScriptParser.ArrayLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GlyphScriptParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionList([NotNull] GlyphScriptParser.ExpressionListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GlyphScriptParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionList([NotNull] GlyphScriptParser.ExpressionListContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace GlyphScriptCompiler.Antlr
