name: Integration Tests

permissions:
  checks: write
  pull-requests: write

on:
  push:
    branches: [main]
    paths:
      - GlyphScriptCompiler/**
      - GlyphScriptCompiler.IntegrationTests/**
      - Dockerfile.test
  pull_request:
    branches: [main]
    paths:
      - GlyphScriptCompiler/**
      - GlyphScriptCompiler.IntegrationTests/**
      - Dockerfile.test
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t glyphscript-test -f Dockerfile.test .

      - name: Run integration tests in Docker
        run: docker run --rm -v ${{ github.workspace }}/TestResults:/app/TestResults glyphscript-test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: TestResults
        if: ${{ always() }}

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: TestResults/**/*.xml
